//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileAssortment.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileAssortment.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string B_Action {
            get {
                return ResourceManager.GetString("B_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダー選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string B_ChooseTargetDir {
            get {
                return ResourceManager.GetString("B_ChooseTargetDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string B_Config {
            get {
                return ResourceManager.GetString("B_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string B_Ok {
            get {
                return ResourceManager.GetString("B_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの仕分けが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string M_AssortComplete {
            get {
                return ResourceManager.GetString("M_AssortComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダーを選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string M_NoSelectFolder {
            get {
                return ResourceManager.GetString("M_NoSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string M_Processing {
            get {
                return ResourceManager.GetString("M_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   想定外のエラーが発生しました。詳細はログに出力されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string M_UnhandledException {
            get {
                return ResourceManager.GetString("M_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルアソーター に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string W_ApplicationTitle {
            get {
                return ResourceManager.GetString("W_ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象フォルダー選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string W_FolderSelectDialog {
            get {
                return ResourceManager.GetString("W_FolderSelectDialog", resourceCulture);
            }
        }
    }
}
